---
- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: /tmp/yay
    update: true

- name: Build yay
  command:
    chdir: "/tmp/yay"
    cmd: "makepkg -sf --noconfirm"

- name : install yay
  shell: |
    pacman -U /tmp/yay/yay-*.pkg.tar.zst --noconfirm
  become: true
