---
- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: ~/yay
    update: true

- name: Build yay
  command:
    chdir: "~/yay"
    cmd: "makepkg -sf --noconfirm"

- name : install yay
  shell: |
    pacman -U /home/{{ ansible_user_id }}/yay/yay-*.pkg.tar.zst --noconfirm
  become: true
