---
- name: install vim
  import_tasks: vim.yml
  tags: vim
  

- name: install neovim
  import_tasks: neovim.yml
  tags: neovim

- name: install vscode
  become: yes
  community.general.pacman:
    name: code
  retries: 6
  tags: vscode

- name: install neovide
  become: yes
  community.general.pacman:
    name: ["neovide","libxkbcommon-x11"]
  retries: 6
  tags: neovide
