---
- name: install dependencies for rt8821ce install
  command: yay -S rtl8821ce-dkms-git --noconfirm
  when: install_wifi == "yes"
  retries: 6

    
- name: build and install driver
  become: yes
  shell: |
    modprobe -r rtw88_8821ce
    echo "blacklist rtw88_8821ce" >> /etc/modprobe.d/blacklist.conf
    modprobe 8821ce
  when: install_wifi == "yes"
