---
- name: disable network-wait-online service
  systemd: 
    name: NetworkManager-wait-online.service
    state: stopped
    enabled: no
  become: yes

- name: disable network dispatch service
  systemd: 
    name: NetworkManager-dispatcher.service
    state: stopped
    enabled: no
  become: yes

  
- name: disable wpa supplicant
  systemd: 
    name: wpa_supplicant.service
    state: stopped
    enabled: no
  become: yes
