--- 
- name: configure sddm
  import_tasks: sddm.yml
  tags: sddm

- name: install wayland & sway
  import_tasks: sway.yml
  tags: sway

- name: install hyprpicker
  community.general.pacman:
    name: hyprpicker
  become: yes
  tags: hypr
  retries: 6

- name: install idle
  command: yay -S sway-audio-idle-inhibit-git --noconfirm
  tags: idle
  retries: 6
