--- 
- name: configure sddm
  import_tasks: sddm.yml
  tags: sddm

- name: install wayland & sway
  import_tasks: sway.yml
  tags: sway

- name: install hyprpicker
  community.general.pacman:
    name: hyprpicker
  become: yes
  tags: hypr
  retries: 6

- name: Installing idle
  kewlfft.aur.aur:
    name: sway-audio-idle-inhibit-git
    state: present
    use: yay
    extra_args: --noconfirm
  become: yes
  tags: idle
  become_user: aur_builder
  retries: 6
