---
- name: Install ZSH
  community.general.pacman:
    name: zsh
  retries: 3
  become: True
  become: yes
    
- name: Change shell to zsh
  shell: usermod --shell /bin/zsh {{ current_user }}
  become: yes
