---
- name: make .ssh dir
  file:
    path: $HOME/.ssh
    state: directory
  tags: ssh

- name: install ssh-key-pass
  community.general.pacman:
    name: x11-ssh-askpass
  retries: 6
  become: True
  tags: ssh

- name: install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags: ssh

- name: install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags: ssh

- name: add ssh key
  shell: |
  { sleep .1; echo {{ ssh_pass }}; } | script -q /dev/null -c 'ssh-add /path/to/identity'
    ssh-add "{{ dest_key }}"
  tags: [ssh_test,ssh]
