---
- name: make .ssh dir
  file:
    path: $HOME/.ssh
    state: directory
  tags: ssh

- name: install ssh-key-pass
  community.general.pacman:
    name: x11-ssh-askpass
  retries: 6
  become: True
  tags: ssh

- name: install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags: ssh

- name: install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags: ssh

- name: add ssh key
  shell: |
    ssh-add "{{ dest_key }}"
    { sleep .1; echo "{{ ssh_pass }}"; } | script -q /dev/null -c "{{ dest_key }}" 
  ignore_errors: True
  tags: [ssh_test,ssh]

- name: connect to github
  shell: |
    ssh -T -o StrictHostKeyChecking=accept-new git@github.com
  ignore_errors: True
  tags: [ssh_test,ssh]
