---
- name: remove directories
  shell: |
     rm -rf /home/{{ ansible_user_id }}/tmux /home/{{ ansible_user_id }}/polybar /home/{{ ansible_user_id }}/picom /home/{{ ansible_user_id }}/.bashrc /home/{{ ansible_user_id }}/.zshrc /home/{{ ansible_user_id }}/.tmux.conf /home/{{ ansible_user_id }}/.profile /home/{{ ansible_user_id }}/.bash_profile
  become: yes

    
# - name: change permissions and modify polybar config
#   shell: |
#      chmod +x ~/bin -R
#      chmod +x ~/.fehbg
#      a=$(ls /sys/class/backlight/)
#      sed -Ei "s/card =.*/card = $a/g" /home/{{ ansible_user_id }}/.dotfiles/polybar/.config/polybar/config
#   tags: polybar
