---
- name: clone dotfiles
  import_tasks: dotfiles.yml
  tags: dotfiles
    
- name: clone wallpapers
  import_tasks: wallpapers.yml
  tags: wallpapers

- name: tinker configs and delete unnecessary directories
  import_tasks: config.yml
  tags: change_config
    
     
- name: install stow
  import_tasks: stow.yml
  tags: stow
    
- name: download fonts
  import_tasks: fonts.yml
  tags: fonts

- name: copy lf files
  shell: |
    chmod +x $HOME/.dotfiles/lf/.config/lf/preview
    chmod +x $HOME/.dotfiles/lf/.config/lf/cleaner
    chmod +x $HOME/.dotfiles/lf/.config/lf/lfrun
    chmod +x $HOME/.dotfiles/lf/.config/lf/lf-command
  tags: chmod_lf

- name: setup brave config
  shell: |
    mkdir -p $HOME/.config/BraveSoftware/Brave-Browser/Default
    cp ~/.dotfiles/brave/Local\ State ~/.config/BraveSoftware/Brave-Browser
    cp ~/.dotfiles/brave/Preferences ~/.config/BraveSoftware/Brave-Browser/Default
    cp ~/.dotfiles/brave/brave-flags.conf ~/.config/
  tags: brave-config

- name: make config dir for openvpn
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - $HOME/.config/openvpn/config/udp
    - $HOME/.config/openvpn/config/tcp
    - $HOME/.config/openvpn/pass/
  tags: openvpn_config


- name: symbolic link brave-browser to brave
  file:
     src: "/usr/bin/brave" 
     dest: "$HOME/usr/bin/brave-browser"
     state: link

- name: symbolic link batcat to bat
  file:
     src: "/usr/bin/bat" 
     dest: "$HOME/usr/bin/batcat"
     state: link

- name: symbolic link for lf-command
  file:
    src: "$HOME/.dotfiles/lf/.config/lf/lf-command"
    dest: "$HOME/usr/bin/lf-command"
    state: link
  tags: lf-command
       
- name: symbolic link for lfrun
  file:
    src: "/$HOME/.dotfiles/lf/.config/lf/lfrun"
    dest: "$HOME/usr/bin/lfrun"
    state: link
  tags: lfrun
       

- name: symbolic link fdfind to fd
  file:
     src: "/usr/bin/fd" 
     dest: "$HOME/usr/bin/fdfind"
     state: link

- name: symbolic link xterm to alacritty
  file:
     src: "/usr/bin/alacritty" 
     dest: "$HOME/usr/bin/xterm"
     state: link

     
- name: copy Network manager config to /etc
  become: True
  shell: |
      cp /home/{{ ansible_user_id }}/.dotfiles/sys_d/NetworkManager.conf /etc/NetworkManager/
  tags: network_manager

- name: setup lf as file picker
  ansible.builtin.copy:
    src: /home/{{ ansible_user_id }}/.dotfiles/bin/bin/system_scripts/lf-wrapper.sh
    dest: /usr/share/xdg-desktop-portal-termfilechooser/lf-wrapper.sh
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
  become: yes
  tags: lf-wrapper
