---
- name: install ripgrep from deb package
  become: yes
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
  tags: ripgrep


- name: install fd-find 
  become: yes
  apt:
    name:
      - fd-find
  tags: fd-find
  ignore_errors: yes
