---
- name: Installing protonvpn-cli
  kewlfft.aur.aur:
    name: protonvpn-cli
    state: present
    use: yay
    extra_args: --noconfirm
  become: yes
  become_user: aur_builder

- name: install gnome-keyring
  community.general.pacman:
    name: gnome-keyring
  retries: 6
  become: yes
