---
- name: install protonvpn-cli
  command: yay -S protonvpn-cli --noconfirm
  retries: 6

- name: install gnome-keyring
  community.general.pacman:
    name: gnome-keyring
  retries: 6
  become: yes
