---
- name: make bin directory insile $HOME/.local
  file:
    path: $HOME/.local/bin
    state: directory
  tags: [ alacritty, fzf, nnn ]
      
- name: install alacritty 
  import_tasks: alacritty.yml
  tags: alacritty

- name: install wezterm
  community.general.pacman:
    name: wezterm
  retries: 6
  become: True
  tags: wezterm

- name: install kitty
  community.general.pacman:
    name: kitty
  retries: 6
  become: True
  tags: kitty
